pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_SESSION_TOKEN     = credentials('AWS_SESSION_TOKEN')
        AWS_DEFAULT_REGION    = 'ap-southeast-1'
        PATH = "${env.PATH}:/opt/homebrew/bin:/opt/homebrew/bin/terraform"
    }
    stages {
        stage('Checkout SCM') {
            steps {
                checkout scmGit(branches: [[name: '*/main']],
                    extensions: [],
                    userRemoteConfigs: [[url: 'https://github.com/KAVERI-G-CAMUNDA/terraform-os-eks.git']])
            }
        }

        stage('Initialize Terraform') {
            steps {
                dir('terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Validate Terraform') {
            steps {
                dir('terraform') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform') {
                    sh 'terraform plan'
                }
                input(message: "Approve Terraform Plan?", ok: "Apply")
            }
        }

        stage('Apply/Destroy EKS Cluster') {
            steps {
                dir('terraform') {
                    sh 'terraform $action --auto-approve'
                }
            }
        }
    }
}
